#!/usr/bin/env bash

worldName=$(cat server.properties | grep level-name | sed -E 's/[^=]+=//g')
worldName=${worldName:-world}
backupFileList=("${worldName}" "${worldName}_nether" "${worldName}_the_end" plugins server.properties *.json *.txt)

if [ -n "$AWS_BUCKET" ]; then
  cat << EOF > .s3cfg
[default]
access_key = ${AWS_ACCESS_KEY}
secret_key = ${AWS_SECRET_KEY}
EOF
  if [ -d world ]; then
    for file in "${backupFileList[@]}"; do
      s3cmd sync ${file} s3://${AWS_BUCKET}/${file}
    done
  else
    s3cmd get --recursive s3://${AWS_BUCKET}/
  fi
  rm .s3cfg
fi

if [ -n "$DROPBOX_ACCESS_TOKEN" ]; then
  filePath="${DROPBOX_BACKUP_FILE:-Minecraft/backup}"
  cat << EOF > .dropbox_uploader
OAUTH_ACCESS_TOKEN=${DROPBOX_ACCESS_TOKEN}
EOF
  if [ -d world ]; then
    tar -czvf "${filePath}.tar.gz"
    bin/dropbox_uploader.sh upload "${filePath}.tar.gz" /
    rm "${filePath}.tar.gz"
  else
    if bin/dropbox_uploader.sh download /"${filePath}.tar.gz"
    then
      tar -xzvf "${filePath}.tar.gz"
      rm "${filePath}.tar.gz"
    fi
  fi
  rm .dropbox_uploader
fi
